services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/public:/app/public
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - social-media-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./vite.config.js:/app/vite.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    depends_on:
      - backend
    networks:
      - social-media-network
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

networks:
  social-media-network:
    driver: bridge
