services:
  app:
    build: .
    container_name: social-media-agent
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://smedia_user:social_media_2024@host.docker.internal:5432/social_media_agent
      GROQ_API_KEY: ${GROQ_API_KEY}
      STABILITY_API_KEY: ${STABILITY_API_KEY}
      GEMINI_API: ${GEMINI_API}
      CHATGPT_API: ${CHATGPT_API}
      NANO_BANANA_API_KEY: ${NANO_BANANA_API_KEY}
      POLL_INTERVAL_MINUTES: ${POLL_INTERVAL_MINUTES}
      POST_WINDOW_SECONDS: ${POST_WINDOW_SECONDS}
      HOST: ${HOST}
      PORT: ${PORT}
      CORS_ORIGINS: ${CORS_ORIGINS}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      FACEBOOK_PAGE_ID: ${FACEBOOK_PAGE_ID}
      GRAPH_API_URL: ${GRAPH_API_URL}
      FACEBOOK_ACCESS_TOKEN: ${FACEBOOK_ACCESS_TOKEN}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      REDDIT_ACCESS_TOKEN: ${REDDIT_ACCESS_TOKEN}
      REDDIT_REFRESH_TOKEN: ${REDDIT_REFRESH_TOKEN}
      REDDIT_USERNAME: ${REDDIT_USERNAME}
      REDDIT_PASSWORD: ${REDDIT_PASSWORD}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
      TWITTER_USERNAME: ${TWITTER_USERNAME}
    ports:
      - "8000:8000"
    volumes:
      - ./server/public:/app/public
      - ./server/.env:/app/.env:ro
      - ./server/Credentials.json:/app/Credentials.json:ro
      - ./server/token.json:/app/token.json
