version: '3.8'

services:
  # Frontend Service (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: social-media-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - social-media-network
    restart: unless-stopped

  # Backend Service (FastAPI + Python)
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: social-media-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - backend-data:/app/data
      - backend-uploads:/app/public/uploads
    environment:
      # Database
      - DATABASE_URL=sqlite:///./data/social_media.db
      
      # Server Configuration
      - PORT=8000
      - HOST=0.0.0.0
      - ENVIRONMENT=development
      
      # API Keys (loaded from .env file)
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      
      # Facebook Configuration
      - PAGE_ID=${PAGE_ID}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      
      # Google Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    env_file:
      - ./server/.env
    networks:
      - social-media-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Define custom network for service communication
networks:
  social-media-network:
    driver: bridge

# Persistent volumes for data storage
volumes:
  backend-data:
    driver: local
  backend-uploads:
    driver: local
